### ISSUE TITLE
Exclude Window names based on Regex?

### ISSUE THREAD

**Issue by wilsongoode** [Jean-Tinland/simple-bar#135]
I have been able to hide some windows like "Microsoft Teams Notification" which has a static naming scheme. However, a window like "Microsoft Teams Call in Progress [Meeting Name]" exhibits the same behavior and can't be blocked because the window name changes with each different meeting.

I don't want to exclude _all_ windows because it is useful to know which desktop a given window is on, except for the floating windows.
<img width="395" alt="Screen Shot 2021-05-24 at 4 02 16 PM" src="https://user-images.githubusercontent.com/45737196/119401429-74ccb600-bca9-11eb-90e6-61796e2fbaad.png">

I think this same behavior would apply to quick-view Finder windows or other preview-style floating windows. 

If there is already a way to exclude like this, please let me know, thanks!

**Comment by Jean-Tinland** [comment]
Hi, this is a good idea! 
I'll try to implement that. I'm thinking of adding a checkbox in order to activate regex syntax in the already existing exclusion inputs in settings.

I'll let you know when I'm done. :)

**Comment by jbbudzon** [comment]
Just piggy backing off of this request, it is very nice that we can exclude items from the spaces widget. This can currently be done for application names or window titles. They are exact matches and this request is for regex.

This would solve many of my issues. For example, I get reminders from Outlook. The title is 1 Reminder, 2 Reminders, 3 Reminders, etc. Regex will allow me to handle this with a single entry.

However, there are situations that may arise where a user cannot exclude something based on the title alone. It may be that the user needs a combination of both application name and window title to determine if this should be excluded or not.

Lastly, I have one very specific case with Zoom where the window title is empty. I'd like to exclude all zoom windows that have an empty title. Regex may be able to handle this case with the string `^$`. So, this may not be much of an issue once regex is supported.

If we'd like to open any new enhancements for these additional (but somewhat related) requests, not a problem at all! I may also be able to work on the code some for submitting a PR. Not sure how much time I'll have 😝

**Comment by Jean-Tinland** [comment]
Hi!

You'll find a new setting in the "Spaces" tab:
![Screenshot 2021-06-25 at 13 36 24](https://user-images.githubusercontent.com/43068795/123419362-6e886d00-d5ba-11eb-8795-1105059c0a09.jpg)

Let me know if it suits you!

**Comment by wilsongoode** [comment]
When I enable regex syntax, I no longer see any window icons in the spaces widget.

With no regex:
<img width="881" alt="Screen Shot 2021-06-28 at 11 48 14 AM" src="https://user-images.githubusercontent.com/45737196/123666088-e64ad780-d806-11eb-9e25-9edf081820c8.png">

Enabling regex:
<img width="690" alt="Screen Shot 2021-06-28 at 11 48 42 AM" src="https://user-images.githubusercontent.com/45737196/123666092-e6e36e00-d806-11eb-9008-b201d5540e03.png">

The result:
<img width="666" alt="Screen Shot 2021-06-28 at 11 48 26 AM" src="https://user-images.githubusercontent.com/45737196/123666094-e77c0480-d806-11eb-96dd-b3bf3a5b0a3a.png">

I would like to be able to do something like this `(Microsoft Teams Notification|Microsoft Teams Call in progress.*)`, but removed the second condition to see if that was causing the issue.

**Comment by wilsongoode** [comment]
After updating, I also noticed the space names and icons are shifted down (no longer vertically centered) and each space has a much wider box around it. Is this unique to my configuration? I need to dig into the css to determine.

**Comment by Jean-Tinland** [comment]
Hi!

There was indeed a problem when the exclusions are empty in regex mode: it wasn't ignored and tested anyway. This is now fixed.

I'm looking for a solution about this spacing problem, thank you for reporting it!

**Comment by Jean-Tinland** [comment]
This is fixed with: 64b97af :)

**Comment by wilsongoode** [comment]
Just git pulled again. The vertical spacing is still a bit off, but the horizontal spacing is perfect! 
<img width="528" alt="Screen Shot 2021-06-28 at 1 31 15 PM" src="https://user-images.githubusercontent.com/45737196/123679118-25802500-d815-11eb-9399-4d0c12496472.png">

**Comment by Jean-Tinland** [comment]
I couldn't reproduce the vertical align bug, are you stil experiencing it?

**Comment by wilsongoode** [comment]
<img width="1280" alt="Screen Shot 2021-07-19 at 11 18 05 AM" src="https://user-images.githubusercontent.com/45737196/126184362-5bffb4e7-bef7-4acd-9636-62830bfd312b.png">
I am still experiencing it. It seems to be only on the spaces widget, but it hasn't been serious enough for me to dive in and figure out why yet. If you can't reproduce it, what should I check on my machine to debug it?

**Comment by jbbudzon** [comment]
I can confirm as well. Here is a screenshot of before the changes:
![Screen Shot 2021-07-19 at 10 09 31 AM](https://user-images.githubusercontent.com/46833444/126330499-8a6a8b91-fb44-46cb-9ff8-d2971e7f9c7b.png)

Here is a screenshot after the changes:
![Screen Shot 2021-07-19 at 10 41 06 AM](https://user-images.githubusercontent.com/46833444/126330528-2ef2e97f-10d2-46f4-81c3-cb19a7cc2379.png)

Oddly enough, it appears that this issue is only present for the spaces widget.

I haven't had any time to dig in and find out why this is happening. I haven't had time to dig into the new regex matching either. So, I've mostly been running the older code.

**Comment by Jean-Tinland** [comment]
I tried to fix this but as I can't reproduce it on my end I don't know if this is really fixed.

Let me know if this is better!

**Comment by wilsongoode** [comment]
<img width="504" alt="Screen Shot 2021-08-05 at 11 19 41 AM" src="https://user-images.githubusercontent.com/45737196/128375835-dc997eb5-e72b-4a21-9299-e74ba681c151.png">
Just updated again. Looks like it worked!

**Comment by jbbudzon** [comment]
Worked for me too!

**Comment by Jean-Tinland** [comment]
Great! Thank you both for testing it!
